In [46]:
import pandas as pd
import numpy as np

## Loading Data From File

In [47]:
df = pd.read_csv('iris.csv')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

### Splitting data Frame into Data and Class(X,y), And Converting them to NumpyArray

In [48]:
df.columns[:-1]

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='object')

In [49]:
#X = df[['sepal_length','sepal_width','petal_length','petal_width']]
X = df[df.columns[:-1]].values
#y = df['species']
y = df[df.columns[-1]].values

In [53]:
X.dtype

dtype('float64')

In [ ]:
X.dtypes

In [54]:
y.dtype

dtype('O')

### Importing ScikitLearn Library for Machine Learning

In [55]:
# train_test_split is responsible to split the data into (Train and Test Data)
from sklearn.cross_validation import train_test_split
# importing Linear Regression classifier
from sklearn.linear_model import LogisticRegression
#importting Baysian Classifier
from sklearn.naive_bayes import GaussianNB
#importing Decision Trees CLassifier
from sklearn.tree import DecisionTreeClassifier
#importing Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
#importing the classification report results
from sklearn.metrics import classification_report
# import confusion matrix
from sklearn.metrics import confusion_matrix
# import metrix to calculate accuacy
from sklearn import metrics

### Splitting dataset into (Train, Test)

In [56]:
(X_train,X_test,y_train,y_test) = train_test_split(X,y,train_size=0.8)

### Train the model Using different classifiers

In [57]:
clf1 = LogisticRegression()
clf1.fit(X_train,y_train)
y_predict = clf1.predict(X_test)

In [58]:
y_predict

array(['versicolor', 'versicolor', 'setosa', 'virginica', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'versicolor', 'versicolor',
       'setosa', 'setosa', 'virginica', 'setosa', 'virginica', 'setosa',
       'virginica', 'versicolor', 'virginica', 'versicolor', 'setosa',
       'virginica', 'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'virginica', 'versicolor'], dtype=object)

In [59]:
y_test

array(['versicolor', 'virginica', 'setosa', 'virginica', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'versicolor', 'versicolor',
       'setosa', 'setosa', 'virginica', 'setosa', 'virginica', 'setosa',
       'virginica', 'versicolor', 'virginica', 'versicolor', 'setosa',
       'virginica', 'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'virginica', 'versicolor'], dtype=object)

In [62]:
print (classification_report(y_test, y_predict))

             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        11
 versicolor       0.92      1.00      0.96        11
  virginica       1.00      0.88      0.93         8

avg / total       0.97      0.97      0.97        30



In [79]:
print(confusion_matrix(y_test,y_predict))

[[15  0  0]
 [ 0 15  4]
 [ 0  0 11]]


In [80]:
print(metrics.accuracy_score(y_test,y_predict))

0.911111111111


In [63]:
clf2 = GaussianNB()
clf2.fit(X_train,y_train)
y_predict = clf2.predict(X_test)

In [64]:
print(confusion_matrix(y_test,y_predict))

[[11  0  0]
 [ 0 10  1]
 [ 0  0  8]]


In [65]:
print(metrics.accuracy_score(y_test,y_predict))

0.966666666667


In [66]:
clf3 = DecisionTreeClassifier()
clf3.fit(X_train,y_train)
y_predict = clf3.predict(X_test)

In [67]:
print(confusion_matrix(y_test,y_predict))

[[11  0  0]
 [ 0 10  1]
 [ 0  1  7]]


In [68]:
print(confusion_matrix(y_test,y_predict))

[[11  0  0]
 [ 0 10  1]
 [ 0  1  7]]
